apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery-worker-deployment
  namespace: production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: celery-worker
  template:
    metadata:
      labels:
        app: celery-worker
    spec:
      containers:
        - name: celery-worker-container
          image: ${DOCKER_USERNAME}/${DOCKER_IMAGE}-backend:latest
          imagePullPolicy: Always
          command:
            - "/bin/sh"
            - "-c"
            - "/app/scripts/celery_worker_entrypoint.sh"
          envFrom:
            - secretRef:
                name: app-secret-config
            - configMapRef:
                name: app-public-config