# Generated by Django 4.2.5 on 2023-12-08 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=128)),
                ('iata_code', models.CharField(blank=True, max_length=4, null=True)),
                ('latitude_deg', models.FloatField()),
                ('longitude_deg', models.FloatField()),
                ('continent', models.CharField(max_length=3)),
                ('iso_country', models.CharField(max_length=3)),
                ('iso_region', models.CharField(max_length=8)),
                ('municipality', models.CharField(max_length=128)),
                ('scheduled_service', models.BooleanField(default=False)),
                ('keywords', models.CharField(blank=True, max_length=256, null=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
