"""
Django setting for backend project.

Generated by 'django-admin startproject' using Django 4.2.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
from os import environ

from split_settings.tools import include

from .hosts import Hosts
import apps

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
PROJECT_NAME = environ.get("PROJECT_NAME", "AufruttenProject")

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!                                         -
SECRET_KEY = environ.get("SECRET_KEY", "django-insecure---------it's---random----default--case-to-change---")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = bool(environ.get("DEBUG", False))

HOSTS = Hosts()
ALLOWED_HOSTS = [HOSTS.backend]
CORS_ALLOWED_ORIGINS = [f"https://{HOSTS.frontend}", ]
CSRF_TRUSTED_ORIGINS = [f"https://{HOSTS.frontend}", f"https://{HOSTS.backend}"]

CORS_ALLOW_ALL_ORIGINS = False
CORS_ALLOW_CREDENTIALS = True

CSRF_USE_SESSIONS = True
CSRF_COOKIE_SECURE = True
SESSION_COOKIE_SECURE = True

CSRF_COOKIE_DOMAIN = f'.{HOSTS.frontend}'
SESSION_COOKIE_DOMAIN = f'.{HOSTS.frontend}'

# Application definition
INSTALLED_APPS = [
    # Default apps
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Health Check
    'health_check',
    'health_check.db',
    'health_check.cache',
    'health_check.storage',
    'health_check.contrib.migrations',
    'health_check.contrib.celery',
    'health_check.contrib.celery_ping',
    'health_check.contrib.redis',

    # Celery
    'django_celery_beat',

    # REST FRAMEWORK - API
    'django_filters',
    'rest_framework',
    'rest_framework_simplejwt',

    # SWAGGER FOR API
    'drf_spectacular',
    'drf_spectacular_sidecar',

    # Social Django - (Social Auth)
    'social_django',

    # CORS
    "corsheaders",

    # Import Export Data
    'import_export',
]

# APPS
INSTALLED_APPS += apps.import_apps()


MIDDLEWARE = [
    # DEFAULT
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'corsheaders.middleware.CorsMiddleware',  # CORS
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'backend' / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',

                # Social Django
                'social_django.context_processors.backends',
                'social_django.context_processors.login_redirect',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "HOST": environ.get("POSTGRES_HOST", "postgres-svc"),
        "PORT": environ.get("POSTGRES_PORT", "5432"),
        "NAME": environ.get("POSTGRES_NAME", "root"),
        "USER": environ.get("POSTGRES_USER", "django"),
        "PASSWORD": environ.get("POSTGRES_PASSWORD", SECRET_KEY),
        "TEST": {"NAME": "test"}
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Europe/Berlin'

USE_I18N = True

USE_TZ = True

LOCALE_PATHS = [BASE_DIR / 'localization']


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
MEDIA_URL = 'media/'

STATIC_ROOT = BASE_DIR / 'staticfiles'
MEDIA_ROOT = BASE_DIR / 'uploads'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
AGE_REMARK = {"MIN": 16, "MAX": 50}  # Old's


# Other settings
include('components/DRF/settings.py')         # Django Rest Framework Settings
include('components/Email/settings.py')       # Email configuration
include('components/OAuth2/settings.py')      # Auth Settings
include('components/Celery/settings.py')      # Celery configuration
include('components/Cloudinary/settings.py')  # Cloudinary configuration
