apiVersion: v1
kind: PersistentVolume
metadata:
  name: backend-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  storageClassName: hostpath
  hostPath:
    path: "/app/backend"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backend-pvc
  namespace: production
spec:
  volumeName: backend-pv
  storageClassName: hostpath
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
