apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-deployment
  namespace: production
spec:
  serviceName: postgres
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      volumes:
        - name: database-data
          persistentVolumeClaim:
            claimName: database-pvc

      containers:
        - name: postgres-container
          image: postgres
          ports:
            - containerPort: 5432
          envFrom:
            - secretRef:
                name: app-secret-config
          volumeMounts:
            - mountPath: /var/lib/postgres/data
              name: database-data
