# Generated by Django 4.2.5 on 2023-10-29 19:47

import apps.accounts.models.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('email', apps.accounts.models.fields.EmailField(max_length=256, unique=True, verbose_name='Email address')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='last login')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='date joined')),
                ('photo', apps.accounts.models.fields.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Photo profile')),
                ('first_name', apps.accounts.models.fields.TitleCharField(max_length=150, verbose_name='First name')),
                ('last_name', apps.accounts.models.fields.TitleCharField(max_length=150, verbose_name='Last name')),
                ('birthday', apps.accounts.models.fields.BirthdayField(verbose_name='Birthday')),
                ('sex', apps.accounts.models.fields.TitleCharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=150, verbose_name='Sex')),
                ('access_token', models.CharField(editable=False, max_length=256, verbose_name='Access token')),
                ('refresh_token', models.CharField(editable=False, max_length=256, verbose_name='Refresh token')),
                ('latest_token_update', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
    ]
