# Generated by Django 4.2.5 on 2024-01-30 10:29

import apps.accounts.fields
import apps.accounts.utils
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('email', apps.accounts.fields.EmailField(max_length=254, unique=True, verbose_name='Email address')),
                ('password', apps.accounts.fields.PasswordField(max_length=128, verbose_name='Password')),
                ('last_login', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Last login')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Date joined')),
                ('last_password_update', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Last password update')),
                ('last_email_received', models.DateTimeField(default=apps.accounts.utils.current_time_timedelta, editable=False, verbose_name='Last email received')),
                ('photo', models.ImageField(null=True, upload_to='', verbose_name='Photo profile')),
                ('first_name', apps.accounts.fields.TitleCharField(max_length=150, verbose_name='First name')),
                ('last_name', apps.accounts.fields.TitleCharField(max_length=150, verbose_name='Last name')),
                ('birthday', apps.accounts.fields.BirthdayField(verbose_name='Birthday')),
                ('sex', apps.accounts.fields.TitleCharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=150, verbose_name='Sex')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
    ]
