apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend-container
          image: ${DOCKER_USERNAME}/${DOCKER_IMAGE}-frontend:latest
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: app-public-config
          volumeMounts:
            - mountPath: /app/dist
              name: html-frontend
      volumes:
        - name: html-frontend
          persistentVolumeClaim:
            claimName: frontend-pvc