name: production CI/CD frontend

on:
  push:
    branches:
      - "main"
    paths:
      - "frontend/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set env
        run: |
          export LOWERCASE_REPO_NAME=$(echo "${{ github.event.repository.name }}" | tr '[:upper:]' '[:lower:]')
          echo "REPO_NAME=${LOWERCASE_REPO_NAME}" >> $GITHUB_ENV
          
          export COMMIT_DATE=$(date --date="${{ github.event.head_commit.timestamp }}" +'%Y.%m.%d-%H.%M.%S')
          echo "NOW=${COMMIT_DATE}" >> $GITHUB_ENV

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.REPO_NAME }}-frontend:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.REPO_NAME }}-frontend:${{ env.NOW }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set env
        run: |
          export LOWERCASE_REPO_NAME=$(echo "${{ github.event.repository.name }}" | tr '[:upper:]' '[:lower:]')
          echo "REPO_NAME=${LOWERCASE_REPO_NAME}" >> $GITHUB_ENV
          
          export COMMIT_DATE=$(date --date="${{ github.event.head_commit.timestamp }}" +'%Y.%m.%d-%H.%M.%S')
          echo "NOW=${COMMIT_DATE}" >> $GITHUB_ENV

      - name: Configure k8s
        uses: azure/k8s-set-context@v1
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBECONFIG }}

      - name: Deploy to Kubernetes
        run: |
          kubectl set image deployment/frontend-deployment frontend-container=${{ secrets.DOCKERHUB_USERNAME }}/${{ env.REPO_NAME }}-frontend:${{ env.NOW }} -n production